// projects/angular/src/app/app.component.ts
import { Component } from '@angular/core';

// import { defineCustomElement } from 'new-cui-demo/dist/esm/es5/new-cui-demo.core';
// import { CuiAlert } from 'new-cui-demo/dist/esm/es5/new-cui-demo.components';

import { defineCustomElement } from '../../../../dist/esm/es5/corporate-ui.core';
import { CuiTheme, CuiHeader, CuiFooter, CuiContent, CuiNavigation, ContextConsumer } from '../../../../dist/esm/es5/corporate-ui.components';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Andreas legendary app';
  items:any = [];
  primaryItems:any = [];

  constructor() {
    this.items = [
      { text: 'global', location: 'https://scania.com/ux-library' },
      { text: 'about', location: 'https://scania.github.io/corporate-ui-docs/developer/' }
    ];

    this.primaryItems = [
      { text: 'home', location: '/' },
      { text: 'contact', location: '/contact' }
    ];

    defineCustomElement(window, [CuiTheme, CuiHeader, CuiFooter, CuiContent, CuiNavigation, ContextConsumer]);
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<cui-theme name="scania"></cui-theme>
<cui-header [siteName]='title' [items]='items'></cui-header>
<cui-content>
  <cui-navigation [primaryItems]='primaryItems'></cui-navigation>

  <div style="text-align:center">
    <h1>
      Welcome to {{ title }}!
    </h1>
    <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
  </div>
  <h2>Here are some links to help you start: </h2>
  <ul>
    <li>
      <h2><a target="_blank" rel="noopener" href="https://angular.io/tutorial">Tour of Heroes</a></h2>
    </li>
    <li>
      <h2><a target="_blank" rel="noopener" href="https://github.com/angular/angular-cli/wiki">CLI Documentation</a></h2>
    </li>
    <li>
      <h2><a target="_blank" rel="noopener" href="https://blog.angular.io/">Angular blog</a></h2>
    </li>
  </ul>
</cui-content>
<cui-footer></cui-footer>

// projects/react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import { defineCustomElement } from '../../../dist/esm/es5/corporate-ui.core';
import {
  CuiTheme,
  CuiHeader,
  CuiFooter,
  CuiContent,
  CuiNavigation,
  ContextConsumer
} from '../../../dist/esm/es5/corporate-ui.components';

class App extends Component {
  constructor(props) {
    super(props);

    this.title = 'A react app';

    this.items = [
      { text: 'global', location: 'https://scania.com/ux-library' },
      {
        text: 'about',
        location: 'https://scania.github.io/corporate-ui-docs/developer/'
      }
    ];

    this.primaryItems = [
      { text: 'home', location: '/' },
      { text: 'contact', location: '/contact' }
    ];

    defineCustomElement(window, [
      CuiTheme,
      CuiHeader,
      CuiFooter,
      CuiContent,
      CuiNavigation,
      ContextConsumer
    ]);
  }

  render() {
    return [
      <cui-theme name="scania" />,
      <cui-header site-name={this.title} items={JSON.stringify(this.items)} />,
      <cui-content>
        ,<cui-navigation primary-items={JSON.stringify(this.primaryItems)} />
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
      </cui-content>,
      <cui-footer />
    ];
  }
}

export default App;
